# Generated by Django 5.1.7 on 2025-06-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_groupchat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='course',
            field=models.CharField(max_length=200),
        ),
    ]
