# Generated by Django 6.0 on 2025-12-06 11:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from django.utils.crypto import get_random_string


def generate_invite_codes(apps, schema_editor):
    """Generate unique invite codes for existing study groups"""
    StudyGroup = apps.get_model('resources', 'StudyGroup')
    used_codes = set()
    
    for group in StudyGroup.objects.all():
        # Generate a unique code
        while True:
            code = get_random_string(12).upper()
            if code not in used_codes:
                used_codes.add(code)
                group.invite_code = code
                group.save(update_fields=['invite_code'])
                break


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_document_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admin_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='editor_groups', to=settings.AUTH_USER_MODEL),
        ),
        # Add invite_code field without unique constraint first
        migrations.AddField(
            model_name='studygroup',
            name='invite_code',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='is_invite_active',
            field=models.BooleanField(default=True),
        ),
        # Run data migration to populate invite codes
        migrations.RunPython(generate_invite_codes, migrations.RunPython.noop),
        # Now alter the field to add unique constraint
        migrations.AlterField(
            model_name='studygroup',
            name='invite_code',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
        migrations.CreateModel(
            name='GroupInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.IntegerField(blank=True, help_text='Maximum number of times this invite can be used', null=True)),
                ('uses_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='resources.studygroup')),
            ],
        ),
    ]
